edition                      = "2024"
style_edition                = "2024"
unstable_features            = true
format_code_in_doc_comments  = true
doc_comment_code_block_width = 120
normalize_doc_attributes     = true
color                        = "Never"
condense_wildcard_suffixes   = true
enum_discrim_align_threshold = 99
format_generated_files       = false
format_macro_matchers        = true
format_macro_bodies          = true
format_strings               = true
hard_tabs                    = true
hex_literal_case             = "Lower"
show_parse_errors            = false
imports_indent               = "Visual"
imports_layout               = "Horizontal"
imports_granularity          = "Crate"
newline_style                = "Unix"
normalize_comments           = true
overflow_delimited_expr      = true
reorder_impl_items           = true
group_imports                = "StdExternalCrate"
reorder_modules              = true
struct_field_align_threshold = 99
tab_spaces                   = 2
use_field_init_shorthand     = true
use_small_heuristics         = "Max"
use_try_shorthand            = true
wrap_comments                = true
indent_style                 = "Block"
max_width                    = 110
fn_single_line               = true
where_single_line            = true
