name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clippy-rustfmt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add clippy
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt --toolchain nightly
          cargo clippy --all
          cargo +nightly fmt --all -- --check
          cargo test --all --verbose
